# Site settings
title: GorillaGive
description: 'Gorilla Give is a new charity platform that connects people and companies to charities in a way that has never been done before. We believe charities should have access to the same engineering resources as the top technology companies. We want to reduce the pay to play barriers that are so heavily engrained in the nonprofit management software industry today. We want to make it easy for those with like-minded values to come together and support the causes they believe in.  This will be made possible through our hosted auction and event software, charitable giving management technology and by integrating these tools with the software you already use. 
<br>
We’re diligently working on the platform.  Follow us to stay updated and get access to our upcoming private beta.'
url: 'http://gorillagive.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'GorillaGive'
  email: info@gorillagive.io
  twitter_username: gorillagive
  facebook_username: gorillagive
  github_username:  gorillagive
  linkedin_username:  gorilla-give
  instagram_username: gorillagive
  feed:

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
