# Cross site information
title: Gorilla Give Charity Platform
company: Gorilla Give
company_title: Gorilla Give, LLC
email: info@gorillagive.com
phone: (425) 405-0269
address: 10400 NE 4th St
city: Bellevue
state: WA
zip: 98004
description: Here at Gorilla Give we aim to make charity software smarter and affordable. Software shouldn't be your burden.
url: 'http://gorillagive.io'
baseurl: /
copyright: 2016 - 2018

# Social Media Links
twitter_link: https://twitter.com/GorillaGive
github_link:  https://github.com/GorillaGive
facebook_link: https://www.facebook.com/GorillaGive
linkedin_link: https://www.linkedin.com/company/gorilla-give
instagram_link: http://instagr.am/gorillagive
pinterest_link: https://www.pinterest.com/gorillagive/

social:
  linkedin: "https://www.linkedin.com/in/"
  twitter: "https://twitter.com/"


# Build settings
markdown: kramdown

# Custom Variables
path:
  css: assets/css
  js: assets/js
  images: assets/images
  videos: assets/video
  fonts: assets/fonts

profiles:
  - name: Dustin Graves
    firstname: Dustin
    title: Founder/Engineer
    blurb: "is a Software Engineer with over 10 years of experience in designing technology solutions. Dustin has BS in Information Technology and has worked in several different industries including defense, telematics and media. Dustin can be found hanging out with his family or cycling."
    gravatar: "http://2.gravatar.com/avatar/5720df6223196d28891dbe8450170dca?s=200"
    twitter: "gravesdustin"
    facebook:
    linkedin: "dustincgraves"